# Generated by Django 2.2.10 on 2021-02-05 10:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('resources', '0019_informationforactionpage_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(max_length=1000)),
                ('geographic_area_text', wagtail.core.fields.RichTextField(blank=True)),
                ('parcel_id_text', wagtail.core.fields.RichTextField(blank=True)),
                ('info_for_action_header', models.CharField(max_length=250)),
                ('info_for_action_top_text', wagtail.core.fields.RichTextField(blank=True)),
                ('info_for_action_bottom_text', wagtail.core.fields.RichTextField(blank=True)),
                ('official_program_reports', wagtail.core.fields.RichTextField(blank=True)),
                ('other_resources_header', models.CharField(max_length=250)),
                ('other_resources_text', wagtail.core.fields.RichTextField(blank=True)),
                ('footer_top', wagtail.core.fields.RichTextField(blank=True)),
                ('footer_bottom', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
