# Generated by Django 2.2.10 on 2021-02-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='info_for_action_bottom_text',
            new_name='info_for_action_bottom',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='info_for_action_top_text',
            new_name='info_for_action_top',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='other_resources_text',
            new_name='other_resources',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='info_for_action_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='other_resources_header',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='geographic_area_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='parcel_id_text',
            field=models.CharField(max_length=1000),
        ),
    ]
