# Generated by Django 2.2.10 on 2021-02-25 05:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_auto_20210224_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='detroit_housing_tools',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='detroit_housing_tools_header',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
