# Generated by Django 2.2.10 on 2021-02-25 06:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_auto_20210224_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='national_housing_tools',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='national_housing_tools_header',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
