# Generated by Django 2.2.10 on 2021-05-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_auto_20210225_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialprogramreportspage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='officialprogramreportspage',
            name='intro',
        ),
    ]
